config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/home', to: 'pages#home', as: 'home_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :workplaces do
    resources :bookings
  end
end

app/models/admin.rb
class Admin< User
  has_many :workplaces
  def admin?
    true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :workplace
  belongs_to :owner
  belongs_to :freeuser
  belongs_to :premiumuser
  validates :owner_id, presence: true
  validates :workplace_id, presence: true
  validates :freeuser_id, presence: { if: -> { premiumuser_id.blank? } }
  validates :premiumuser_id, presence: { if: -> { freeuser_id.blank? } }
end

app/models/freeuser.rb
class Freeuser < User
  has_many :bookings, dependent: :destroy
  has_many :workplaces, through: :bookings
  def freeuser?
    true
  end
end

app/models/owner.rb
class Owner < User
  has_many :workplaces, dependent: :destroy
  has_many :bookings, dependent: :destroy
  def owner?
    true
  end
end

app/models/premiumuser.rb
class Premiumuser < User
  has_many :bookings, dependent: :destroy
  has_many :workplaces, through: :bookings
  def premiumuser?
    true
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def freeUser?
    false
  end
  def premiumUser?
    false
  end
  def owner?
    false
  end
  def admin?
    false
  end
end

app/models/workplace.rb
class Workplace < ApplicationRecord
  belongs_to :owner
  belongs_to :admin
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :area, presence: true
  validates :category, presence: true
  #mount_uploader :picture, PhotoUploader
  #geocoded_by :location
  #after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @areas = ['North Israel',
      "Central Israel",
      "South Israel",
      "Tel Aviv",
      "Jerusalem",
      "Haifa",
      "Golan"]
    @search_area = params[:search]
    @user = current_user
  end
end

app/controllers/workplaces_controller.rb
class WorkplacesController < ApplicationController
  def index
    @workplaces = Workplace.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DIGITAL VALLEY</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="back-video">
  <div class="banner-content">
    <h1>Welcome to Digital Valley</h1>
    <p>Productivity, comfort, and belongings, everywhere you from</p>
    <%= simple_form_for "area", url: workplaces_path, method: 'get' do |f| %>
        <%= f.input :area, collection: @areas, prompt: :translate %>
        <%= f.submit "search", class: 'btn btn-primary form-group' %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "temp_logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "BECOME A HOST",'/', class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "LOG IN"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "BECOME A MEMBER",'/', class: "navbar-wagon-link become_a_member_btn" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/workplaces/index.html.erb
<ul>
  <% @workplaces.each do |workplace| %>
    <li><%= workplace.name %></li>
  <% end %>
</ul>